### PR TITLE
#1003: added test cases for /v3/covid-19/continents with /oceania or /australia

### PR DESCRIPTION
**Pull request by neo7337**
Test cases added for australia and oceania

### CODE REVIEW

**Comment by ebwinters** [comment]
does adding test cases fix the bug?

**Comment by neo7337** [comment]
I don't think it's a bug, just the test cases were missing for this scenario

**Comment by ebwinters** [comment]
this is the bug https://disease.sh/v3/covid-19/continents/oceania

That does not work

**Comment by ebwinters** [comment]
Also why aren't the test cases running

**Comment by neo7337** [comment]
> this is the bug https://disease.sh/v3/covid-19/continents/oceania
> 
> That does not work

the endpoint works with strict=false as the endpoint has strict=true set by default

https://disease.sh/v3/covid-19/continents/oceania?strict=false

**Comment by neo7337** [comment]
> Also why aren't the test cases running

seems like the builds are queued

**Comment by ebwinters** [comment]
https://twitter.com/githubstatus/status/1393951720946946048?s=20 lol

**Comment by ebwinters** [comment]
@neo7337 here is the real issue:
"[{\"updated\":1621255355887,\"cases\":65926,\"todayCases\":10,\"deaths\":1225,\"todayDeaths\":null,\"recovered\":61834,\"todayRecovered\":6,\"active\":2867,\"critical\":3,\"casesPerOneMillion\":1542.95,\"deathsPerOneMillion\":28.67,\"tests\":19909293,\"testsPerOneMillion\":465961.46,\"population\":42727338,\"continent\":\"**Australia/Oceania**\",\"undefined\":null,\"activePerOneMillion\":67.1,\"...

We need to create some alias for Australia and Oceania to map to this key.

**Comment by puf17640** [comment]
> We need to create some alias for Australia and Oceania to map to this key.

or we could split it at "/" and then just check if the specified keyword is either one of them i guess? what do you think? feels like a hotfix but i can't think of a good workaround for this

**Comment by puf17640** [comment]
currently testing this PR

**Review by ebwinters — APPROVED** [review]

**Pull request merged**
