### PR TITLE
Fix undefined column with worldometers :tea:

### PR DESCRIPTION
**Pull request by mrnonz**
```json
{
  "updated": 1626623147556,
  "country": "Thailand",
  "countryInfo": {
    "_id": 764,
    "iso2": "TH",
    "iso3": "THA",
    "lat": 15,
    "long": 100,
    "flag": "https://disease.sh/assets/img/flags/th.png"
  },
  "cases": 403386,
  "todayCases": 11397,
  "deaths": 3341,
  "todayDeaths": 101,
  "recovered": 283910,
  "todayRecovered": 5726,
  "active": 116135,
  "critical": 3464,
  "casesPerOneMillion": 5764,
  "deathsPerOneMillion": 48,
  "tests": 8129670,
  "testsPerOneMillion": 116167,
  "population": 69982529,
  "continent": "Asia",
  "oneCasePerPeople": 173,
  "oneDeathPerPeople": 20947,
  "oneTestPerPeople": 9,
  "undefined": 1659,
  "activePerOneMillion": 1659.49,
  "recoveredPerOneMillion": 4056.87,
  "criticalPerOneMillion": 49.5
}
```
Remove `"undefined": 1659,` line

### CODE REVIEW

**Comment by mrnonz** [comment]
PR for #1017

**Comment by ebwinters** [comment]
thanks for this PR, looks good. What are the columns causing undef. values?

**Comment by mrnonz** [comment]
@ebwinters I think 3 of theses columns

Screen Shot 2564-07-18 at 23 42 08

**Comment by mrnonz** [comment]
This column is duplicate with our key `activePerOneMillion`

```json
  "undefined": 1659,
  "activePerOneMillion": 1659.49,
```

Screen Shot 2564-07-18 at 23 58 51

**Review by ebwinters — APPROVED** [review]

**Comment by ebwinters** [comment]
@mrnonz  nice dude thanks

**Pull request merged**
