### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by apollyon600**
I haven't touched this API in a bit as I left the team a long time ago.
Although I just wanted to request a pull request to update my website <3

You don't have to, but it'll make my day.

### CODE REVIEW

**Comment by ebwinters** [comment]
yooo how much of the donations have you collected lol. The buy me a coffee is still linked to your account and people seem to be donating

**Comment by puf17640** [comment]
> yooo how much of the donations have you collected lol. The buy me a coffee is still linked to your account and people seem to be donating

totally forgot about this, but yeah... we really need to talk about this...

**Comment by apollyon600** [comment]
> yooo how much of the donations have you collected lol. The buy me a coffee is still linked to your account and people seem to be donating

Haven't gotten a donation in months and I am assuming you removed the link long ago.
image

But since you're asking where the money went, here.

**Comment by apollyon600** [comment]
Havent gotten a donation since December of 2020

**Pull request closed without merging**
