### PR TITLE
Darkmode

### PR DESCRIPTION
**Pull request by Zentreax**
Added Darkmode with the new CSS Media Tag.

Screenshots:
https://zentreax.dev/img/aL4dYTPO.png
https://zentreax.dev/img/ydaLVqRN.png
https://zentreax.dev/img/AsLrdyHJ.png

Please Note:
I don't know how it looks with the Chart since it didn't work on my fork, feel free to edit it.

### CODE REVIEW

**Comment by EliteDaMyth** [comment]
@Zentreax any specific reason to not include the postman logo?

**Comment by Zentreax** [comment]
It wasn't there when I cloned the repo. The only change I made was adding the media query in the CSS.

**Comment by ebwinters** [comment]
ignore tests - this is a different issue

How is darkmode being enabled? I see no switch added to the HTML

**Comment by Zentreax** [comment]
Using the new CSS Media Query.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by ebwinters** [comment]
> Using the new CSS Media Query.
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

cool. Do you have screenshots of how this looks

**Comment by Zentreax** [comment]
> cool. Do you have screenshots of how this looks

They are in the description of this pull request...

**Comment by ebwinters** [comment]
LGTM

**Review by ebwinters — APPROVED** [review]

**Comment by EliteDaMyth** [comment]
@all-contributors please add @Zentreax for code

**Pull request merged**
