### PR TITLE
Some commenting in getUK.js

### PR DESCRIPTION
**Pull request by 1CM69**
A little commenting to shows which metrics have been used with a link provided to source page.

### CODE REVIEW

**Comment by 1CM69** [comment]
OK, trying to understand why ESlint is failing:

`27:18  error  Trailing spaces not allowed  no-trailing-spaces`

I cannot see any trailing spaces on line27 column18

for me all I see is the 'a' at that location in `// Daily total`

Line 32 does not fail & that follows a previous comment too, similar to line 27

**Comment by ebwinters** [comment]
There is a trailing space at the end of that line tho

**Comment by 1CM69** [comment]
> There is a trailing space at the end of that line tho

That's very odd as I have Sublime with default settings:

```
// Trims white space added by auto_indent when moving the caret off the
// line.
"trim_automatic_white_space": true,
```

**Comment by 1CM69** [comment]
Right, third times a charm.

**Pull request closed without merging**
