### PR TITLE
add new website

### PR DESCRIPTION
**Pull request by maltejur**
See #996

@ebwinters I've tried to add the function but I can't seem to get the captcha working (the token returned is `null`). Are you familiar with recaptcha and know what the problem is here? The docs are pretty confusing.
https://github.com/maltejur/API/blob/7ba4280713ad0374add776408d5bff701038b9a0/public/assets/js/index.js#L219

### CODE REVIEW

**Comment by ebwinters** [comment]
I beleive the Token is stored in our prod config, so you don't have access. I can generate a short term one for you to test and share it with you tho, just let me know @maltejur

**Comment by maltejur** [comment]
I found the error, the recaptcha public key for the website is for v2 but I used the code for v3. After creating new keys for recaptcha and mailgun for testing, I could successfully add my email to a mailgun mailing list, so it should work, you just need a v3 recaptcha key.

**Comment by ebwinters** [comment]
> I found the error, the recaptcha public key for the website is for recaptcha v2 but I used the code for v3. After creating new keys for recaptcha and mailgun for testing, I could successfully add my email to a mailgun mailing list, so it should work, you just need a v3 recaptcha key.

So do you need anything on my end? Where did you get a v3/v2 key?

**Comment by maltejur** [comment]
You would need to create a new production token for Recaptcha v3 [here](https://www.google.com/recaptcha/admin/create) and replace the public and private key. Then everything should work.

**Comment by ebwinters** [comment]
> You would need to create a new production token for Recaptcha v3 [here](https://www.google.com/recaptcha/admin/create) and replace the public and private key. Then everything should work.

@maltejur The public key needs to be in the PR right? Also what happened to this PR? There are no touched files

**Comment by maltejur** [comment]
> The public key needs to be in the PR right?

Yes, specifically [here](https://github.com/maltejur/API/blob/fcdbfffc70ef08ef490af4473116b8c1817ea4c1/public/assets/js/index.js#L228) and [here](https://github.com/maltejur/API/blob/fcdbfffc70ef08ef490af4473116b8c1817ea4c1/public/assets/js/index.js#L224)

**Comment by puf17640** [comment]
@ebwinters lmao the pull bot seems to have fucked over this PR heavily 🤣

**Comment by ebwinters** [comment]
Dude what is the pull bot I've never seen it @puf17640

**Comment by maltejur** [comment]
> Dude what is the pull bot I've never seen it @puf17640 

Nah thats my fault, I set up the bot to keep my forks up to date. It seems I shouldn't open prs from the master branch with this bot.

**Pull request closed without merging**
